version: '3.6'
services:

  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/export:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 81:80
    environment:
      - PMA_HOST=mariadb
    depends_on: 
      - mariadb

  web:
    build: .
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/html
